[build-system]
requires = ["maturin>=0.12,<0.13"]
build-backend = "maturin"

[project]
name = "pypipegraph2"
requires-python = ">=3.7"
dependencies = [
	"loguru",
	"rich",
	"xxhash",
	"wrapt",
	"deepdiff",
	"psutil",
	"networkx",
]
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]


[tool.pytest.ini_options]
pythonpath = "python"
